### ISSUE TITLE
Day numbers are transparent in Huawei device

### ISSUE THREAD

**Issue by muhammad-naderi** [alirezaafkar/SunDatePicker#31]
سلام
من مدتهاست از کتابخونه خوبتون دارم روی دستگاه های مختلف استفاده می کنم.
اما جدیدا به مشکلی برخوردم،
 عدد هایی که در 
gridview
  و کلا در 
Viewpager
 هستن انگار ترنسپرنت شدن.
view 
ها هستن، وقتی روی جاهاشون تاچ میشه، تاریخ عوض میشه و ... ولی انگار عدد ها ترنسپرنت هستن.
راه حلی به نظرتون میاد؟

**Comment by muhammad-naderi** [comment]
این کد روی دیوایس ها و اندروید های مختلف اوکی بوده ولی همین APK روی هوآوی با اندروید ۷اینجوری میشه

**Comment by muhammad-naderi** [comment]
![img_20170926_183754](https://user-images.githubusercontent.com/8791318/30897458-3b628e98-a363-11e7-83f9-8f7ec2939e11.jpg)

**Comment by omidheshmatinia** [comment]
سلام. مشکلت فقط با همین گوشیه ؟!
کدت رو بقیه گوشی ها درست کار می کنه ؟!
@muhammad-naderi

**Comment by muhammad-naderi** [comment]
والا تنها جایی که دیدم روی این تبلت هست 
Huawei MediaPad T3
روی بقیه دیوایس هایی که امتحان شده تا حالا مشکلی دیده نشده
7 تا دستگاه تست 
و حدود دو سال کاربرهای فعال برنامه

**Comment by omidheshmatinia** [comment]
امکانش هست لطف کنی فیلم بگیری از صفحه وقتی تاچ میکنه رو جاهای خالی و عکس العمل نشون میده.
همینطور لطفا روی سال کلیک کن ببینم منوی تغییر سالش میاد.
@muhammad-naderi

**Comment by muhammad-naderi** [comment]
سعی می کنم براتون فیلم بگیرم
اما سالها هم هیمن هست
آیتم ها هستن
تاچ که میشه همه چی درست عمل میکنه بجز رنگ فونت نوشته های سال یا روز ها
انگار اون ها ترنسپرنت هستن

**Comment by muhammad-naderi** [comment]
بعد از آپدیت کردن به آخرین نسخه این خطا رو میگیرم

```
09-27 11:28:40.741 8492-8492/package W/System.err: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class ImageView
09-27 11:28:40.743 8492-8492/package W/System.err: Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class ImageView
09-27 11:28:40.752 8492-8492/package W/System.err: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0101c4 a=4}
09-27 11:28:40.756 8492-8492/package W/System.err:     at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
09-27 11:28:40.759 8492-8492/package W/System.err:     at android.widget.ImageView.<init>(ImageView.java:164)
09-27 11:28:40.763 8492-8492/package W/System.err:     at android.widget.ImageView.<init>(ImageView.java:152)
09-27 11:28:40.766 8492-8492/package W/System.err:     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:60)
09-27 11:28:40.770 8492-8492/package W/System.err:     at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
09-27 11:28:40.774 8492-8492/package W/System.err:     at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
09-27 11:28:40.778 8492-8492/package W/System.err:     at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
09-27 11:28:40.782 8492-8492/package W/System.err:     at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
09-27 11:28:40.787 8492-8492/package W/System.err:     at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
09-27 11:28:40.791 8492-8492/package W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:280)
09-27 11:28:40.795 8492-8492/package W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
09-27 11:28:40.798 8492-8492/package W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
09-27 11:28:40.801 8492-8492/package W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
09-27 11:28:40.805 8492-8492/package W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
09-27 11:28:40.808 8492-8492/package W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
09-27 11:28:40.812 8492-8492/package W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
09-27 11:28:40.815 8492-8492/package W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
09-27 11:28:40.819 8492-8492/package W/System.err:     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
09-27 11:28:40.822 8492-8492/package W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
09-27 11:28:40.826 8492-8492/package W/System.err:     at com.alirezaafkar.sundatepicker.fragments.MonthFragment.onCreateView(MonthFragment.java:44)
09-27 11:28:40.830 8492-8492/package W/System.err:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
09-27 11:28:40.832 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
09-27 11:28:40.834 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
09-27 11:28:40.836 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
09-27 11:28:40.838 8492-8492/package W/System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
09-27 11:28:40.840 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
09-27 11:28:40.841 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
09-27 11:28:40.843 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
09-27 11:28:40.845 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
09-27 11:28:40.847 8492-8492/package W/System.err:     at android.support.v4.app.Fragment.performStart(Fragment.java:2214)
09-27 11:28:40.849 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
09-27 11:28:40.851 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
09-27 11:28:40.853 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
09-27 11:28:40.855 8492-8492/package W/System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
09-27 11:28:40.857 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
09-27 11:28:40.858 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
09-27 11:28:40.860 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
09-27 11:28:40.861 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
09-27 11:28:40.863 8492-8492/package W/System.err:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
09-27 11:28:40.864 8492-8492/package W/System.err:     at android.os.Handler.handleCallback(Handler.java:761)
09-27 11:28:40.866 8492-8492/package W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
09-27 11:28:40.867 8492-8492/package W/System.err:     at android.os.Looper.loop(Looper.java:156)
09-27 11:28:40.869 8492-8492/package W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6585)
09-27 11:28:40.870 8492-8492/package W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-27 11:28:40.871 8492-8492/package W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
09-27 11:28:40.872 8492-8492/package W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

```
با این کد دارم میسازم
```

new com.alirezaafkar.sundatepicker.DatePicker
                .Builder()
                .id(new Random().nextInt())
                .build(this)
                .show(fragmentManager, "datePicker");

```

مشکل از style به نظرم میرسه باشه
احتمالا مشکل قبلی هم همین بوده
چجوری و کجا باید ?android:textColorPrimary رو override کنم

به نظر تنها imageView اینجاست
https://github.com/alirezaafkar/SunDatePicker/blob/3f29561a207049177c0bb470a439711a9b477451/sundatepicker/src/main/res/layout/fragment_month.xml

**Comment by alirezaafkar** [comment]
فکر می‌کنم رنگ عددها با پس‌زمینه یکی باشه.
دوتا استایل توی کد تعریف شده. اونا رو ببینید

**Comment by muhammad-naderi** [comment]
با فورس ست کردن استایل مشکل حل شد.
متشکر
