### ISSUE TITLE
npe‌در هنگام چرخش صفحه

### ISSUE THREAD

**Issue by muhammad-naderi** [alirezaafkar/SunDatePicker#32]
سلام

وقتی برنامه rotate میشه 
خطای زیر نشون داده می شه و برنامه crash‌می کنه

```

09-27 14:15:33.895 13354-13354/package W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{package/package.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int com.alirezaafkar.sundatepicker.interfaces.DateInterface.getYear()' on a null object reference
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4121)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:153)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.os.Looper.loop(Looper.java:148)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5480)
09-27 14:15:33.895 13354-13354/package W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-27 14:15:33.895 13354-13354/package W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-27 14:15:33.895 13354-13354/package W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-27 14:15:33.895 13354-13354/package W/System.err: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int com.alirezaafkar.sundatepicker.interfaces.DateInterface.getYear()' on a null object reference
09-27 14:15:33.895 13354-13354/package W/System.err:     at com.alirezaafkar.sundatepicker.fragments.MonthFragment.onViewCreated(MonthFragment.java:74)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2207)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2207)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
09-27 14:15:33.895 13354-13354/package W/System.err:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
09-27 14:15:33.896 13354-13354/package W/System.err:     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
09-27 14:15:33.896 13354-13354/package W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
09-27 14:15:33.896 13354-13354/package W/System.err:     at android.app.Activity.performStart(Activity.java:6334)
09-27 14:15:33.896 13354-13354/package W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2410)
09-27 14:15:33.896 13354-13354/package W/System.err: 	... 10 more

```

**Comment by alirezaafkar** [comment]
سلام. در آخرین نسخه این مشکل حل شده.
