### ISSUE TITLE
DateInterface.getYear()' on a null object reference

### ISSUE THREAD

**Issue by abbasalim** [alirezaafkar/SunDatePicker#47]
سلام. برخی کاربرای من بعضی اوقات با خطای زیر روبرو میشن:

`Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.esfandune.wave/ir.esfandune.wave.LoanPart.activity.AddInstallmentActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int com.alirezaafkar.sundatepicker.interfaces.DateInterface.getYear()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2466)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4168)
	at android.app.ActivityThread.access$1300(ActivityThread.java:152)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int com.alirezaafkar.sundatepicker.interfaces.DateInterface.getYear()' on a null object reference
	at com.alirezaafkar.sundatepicker.fragments.MonthFragment.onViewCreated(MonthFragment.java:74)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2361)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1451)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1224)
	at android.app.Activity.performStart(Activity.java:6032)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 11 more
`

**Comment by miladcoder** [comment]
جنس ایرانیه دیگه ... چه توقعی داری ؟
مشکل که داره هیچ... جواب سوال هم نمیده

**Comment by alirezaafkar** [comment]
@miladcoder دوست عزیز مگر بابت این کتابخونه پولی دریافت شده یا ضمانت داده‌م که تا ابد به‌روز رسانی کنم که انقدر طلبکار هستید؟
این کتابخونه متن‌باز هست و می‌تونید در توسعه‌ی اون کمک کنید و مشکلاتش رو برطرف کنید.

**Comment by miladcoder** [comment]
کسی از پول حرف نزد . منم طلب کار نیستم 
اما مثل اینکه شما فقط یه کد گزاشتی که بگی منم هستم وگرنه مشکل کد خودت رو برطرف میکردی .

**Comment by ShalbafZadeh** [comment]
@miladcoder 
نرم افزار ها لایسنس دارن و لایسنس شرایط استفاده رو مشخص میکنه
https://github.com/alirezaafkar/SunDatePicker/blob/master/README.md
اخر این فایل لایسنس نوشته شده 
"AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
این لایبرری  دقیقا به همین شکلی که هست بدون هیچ وارانتی یا شزایطی به هیچ نوع توضیح شده و توسعه دهنده مطلقا مسولیتی درباره رفع مشکلات شما و سایر یوزر ها نداره .
این جا هم میتونید لایسنس های معروف رو ببینید 
https://choosealicense.com/licenses/
هیچ کدوم هیچگونه ضمانتی برای کارکرد به شما نمی دن

**Comment by mohsen202** [comment]
ممنون بابت زحمتی که میکشید.. من به جای دیگران که شما رو آزرده کردند عذر میخوام

**Comment by abbasalim** [comment]
آقا علیرضا امیدوارم. این مباحث حاشیه ای اصل مسئله که حل مشکل هست .یادتون نره
